- name: Build Tweak
  run: |
    make clean
    make package FINALPACKAGE=1

- name: Find outputs (Debug)
  run: |
    echo "=== SEARCHING FOR OUTPUT FILES ==="
    find . -name "*.deb"
    find . -name "*.dylib"

- name: Upload Artifact
  uses: actions/upload-artifact@v4
  with:
    name: MostashUltra
    path: |
      packages/*.deb
      packages/**/*.deb
      .theos/**/obj/**/*.dylib
