Theos isn’t using all available CPU cores on this computer. Consider upgrading GNU Make: https://theos.dev/docs/parallel-building
==> Warning: Building for iOS 12.0, but the current toolchain can’t produce arm64e binaries for iOS earlier than 14.0. More information: https://theos.dev/docs/arm64e-deployment
> Making all for tweak MostashUltra…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
==> Linking tweak MostashUltra (arm64)…
ld: warning: -multiply_defined is obsolete
==> Generating debug symbols for MostashUltra…
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64e)…
==> Linking tweak MostashUltra (arm64e)…
ld: warning: -multiply_defined is obsolete
==> Generating debug symbols for MostashUltra…
==> Merging tweak MostashUltra…
==> Signing MostashUltra…
bash: ldid: command not found
make[2]: *** [/Users/runner/work/MostashUltraApp/MostashUltraApp/.theos/obj/debug/MostashUltra.dylib] Error 127
rm /Users/runner/work/MostashUltraApp/MostashUltraApp/.theos/obj/debug/MostashUltra.dylib.804c181c.unsigned
make[1]: *** [internal-library-all_] Error 2
make: *** [MostashUltra.all.tweak.variables] Error 2
Error: Process completed with exit code 2.
